### PR TITLE
Support for entrypoints and multi compiler

### PR DESCRIPTION
**Pull request by pustovalov**
Thanks for an amazing webpack plugin.

I'm using https://github.com/rails/webpacker (which uses this package https://github.com/rails/webpacker/blob/v4.2.0/package.json#L50) with multiple webpack configs

Webpacker does not have the option to generate different entrypoints using `entrypointsKey`
https://github.com/rails/webpacker/blob/v4.2.0/lib/webpacker/manifest.rb#L26
or use two different manifests
https://github.com/rails/webpacker/blob/v4.2.0/lib/webpacker/configuration.rb#L50

At the moment I have webpacker v. 4.0.7 with this workaround https://github.com/webdeveric/webpack-assets-manifest/issues/48#issuecomment-470443650

When upgrading a webpacker to a version 4.2.0, the workaround above has stopped working

What have I done in this PR:

1. Added support for merging entrypoints when `options.merge=true`
Use case
webpack has multiple configurations: `webpack([{}, {}])`
`options.merge=true`
compile all of this by `parallel-webpack`

2. Added support for merging entrypoints when `options.merge=false`
Use case
webpack has multiple configurations: `webpack([{}, {}])`
`options.merge=false`
compile this in one thread

Example of master + specs from this PR:
https://github.com/webdeveric/webpack-assets-manifest/compare/master...pustovalov:specs-with-master-code
https://travis-ci.com/pustovalov/webpack-assets-manifest/jobs/264353096

### CODE REVIEW

**Comment by pustovalov** [comment]
@webdeveric hey, WDYT about this PR?

**Comment by justin808** [comment]
Hi @pustovalov,
Why would does parallel-webpack make a difference regarding whether or not merge is used?

Hi @webdeveric,
Would a more generic deep merge on all keys potentially be more useful? Or, regarding entrypoints, is there an underlying assumption that we different webpack config builds would have different entrypoints?

**Comment by pustovalov** [comment]
Hey @justin808,

you can try to use the version from this PR:
```
"dependencies": {
  "webpack-assets-manifest": "^3.1.1"
},
"resolutions": {
  "webpack-assets-manifest": "https://github.com/pustovalov/webpack-assets-manifest#build"
}
```

**Comment by pustovalov** [comment]
Hey @webdeveric, can you take a look?

**Comment by webdeveric** [comment]
@pustovalov I'll try to review this week. I'm in the middle of adding Webpack 5 support at the moment.

**Comment by webdeveric** [comment]
@pustovalov Thanks for the effort, but I going to close this one.
I've already updated the merge behavior to use lock files and `deepmerge`.
If you want to follow along, its in my `dev` branch. I'll try to release an update soon.

**Pull request closed without merging**
